# Generated by Django 5.2.1 on 2025-05-26 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=100, verbose_name='Nome da Marca')),
                ('nome_modelo', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('descricao_modelo', models.TextField(blank=True, null=True, verbose_name='Descrição do Modelo')),
                ('ano_modelo', models.PositiveIntegerField(verbose_name='Ano do Modelo do Veículo')),
            ],
            options={
                'verbose_name': 'Modelo de Veículo',
                'verbose_name_plural': 'Modelos de Veículos',
                'ordering': ['nome_marca', 'nome_modelo'],
                'unique_together': {('nome_marca', 'nome_modelo', 'ano_modelo')},
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ano_fabricacao', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor do Veículo')),
                ('descricao_carro', models.TextField(blank=True, null=True, verbose_name='Descrição do Carro/Modelo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carros_especificos', to='veiculos.modelo', verbose_name='Modelo Específico do Veículo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
