# Generated by Django 5.2.1 on 2025-05-26 09:00

import veiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to=veiculos.models.get_upload_path_imagem_carro, verbose_name='Imagem Principal do Veículo'),
        ),
    ]
