# Generated by Django 5.2.3 on 2025-06-19 13:04

import django.db.models.deletion
import veiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_carro_imagem_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=veiculos.models.get_upload_path_imagem_carro, verbose_name='Imagem do Veículo')),
                ('e_principal', models.BooleanField(default=False, verbose_name='É imagem principal')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='veiculos.carro', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Imagem do Veículo',
                'verbose_name_plural': 'Imagens dos Veículos',
                'ordering': ['-e_principal', 'ordem', 'data_upload'],
                'unique_together': {('carro', 'e_principal')},
            },
        ),
    ]
