# Generated by Django 5.2.3 on 2025-06-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_imagemcarro'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagemcarro',
            unique_together=set(),
        ),
    ]
